using System.Net;using System.Text.Json;using Xunit;using WatchWeaver.Jellyfin.Capture;using WatchWeaver.Jellyfin.Delivery;using WatchWeaver.Jellyfin.Protocol;using WatchWeaver.Jellyfin.Queue;
namespace WatchWeaver.Jellyfin.Tests;
public sealed class CoreTests
{
    private static EventEnvelope E(string id="one")=>new(1,id,"played",DateTimeOffset.Parse("2026-09-03T16:00:00Z"),new("s","10.11.0"),new("0.1.0","10.11.0.0"),new("u"),new("i","movie","Movie"),new(true));
    [Fact]public void OverlappingSignalsShareIdButRewatchDoesNot(){var c=new EventCorrelation(TimeSpan.FromSeconds(30));var at=DateTimeOffset.UtcNow;var a=c.GetEventId("s","u","i",1,at,"played");Assert.Equal(a,c.GetEventId("s","u","i",1,at.AddSeconds(2),"marked_played"));Assert.NotEqual(a,c.GetEventId("s","u","i",2,at.AddMinutes(5),"played"));}
    [Fact]public async Task QueueSurvivesRestartAndReportsOverflow(){var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");try{var q=new OutboundQueue(p,1);Assert.True(await q.EnqueueAsync(E()));Assert.False(await q.EnqueueAsync(E("two")));var q2=new OutboundQueue(p,1);await q2.LoadAsync();var s=await q2.StatusAsync();Assert.Equal(1,s.Pending);Assert.Equal(1,s.OverflowCount);Assert.Equal(E().OccurredAt,s.OldestPendingAt);}finally{File.Delete(p);}}
    [Fact]public async Task PermanentFailureDeadLettersWithoutLeakingToken(){var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");try{var q=new OutboundQueue(p);await q.EnqueueAsync(E());var handler=new Handler(_=>new(HttpStatusCode.BadRequest));var d=new Dispatcher(new HttpClient(handler),q,()=>(new Uri("http://127.0.0.1:1/"),"secret-token"));await d.DeliverOneAsync(DateTimeOffset.UtcNow);var s=await q.StatusAsync();Assert.Equal(0,s.Pending);Assert.Equal(1,s.DeadLetters);Assert.DoesNotContain("secret",s.LastErrorCode);}finally{File.Delete(p);}}
    [Fact]public void SeasonInventorySeparatesReleasedFutureAndWatched(){var inventory=SeasonInventory.From([new(1,false,true),new(2,false,true),new(3,true,false)]);Assert.Equal(2,inventory.ReleasedCount);Assert.Equal(2,inventory.WatchedReleasedCount);Assert.Equal(1,inventory.FutureCount);Assert.Equal(2,inventory.LatestReleasedEpisodeNumber);}
    [Fact]public void EpisodePayloadUsesStableHierarchyAndInventoryContract(){var item=new ItemInfo("episode","episode","Finale",SeriesTitle:"Show",SeriesId:"series",SeasonId:"season",SeasonNumber:3,EpisodeNumber:10,SeriesProviderIds:new Dictionary<string,string>{{"tvdb","123"}},SeasonEpisodeCount:10,SeasonWatchedEpisodeCount:10,SeasonFutureEpisodeCount:0,LatestReleasedEpisodeNumber:10);var json=JsonSerializer.Serialize(item);Assert.Contains("\"series_id\":\"series\"",json);Assert.Contains("\"season_id\":\"season\"",json);Assert.Contains("\"season_episode_count\":10",json);Assert.Contains("\"latest_released_episode_number\":10",json);}
    [Fact]public void RetryBackoffIncludesBoundedJitter(){Assert.Equal(TimeSpan.FromSeconds(4),Dispatcher.Backoff(0,.8));Assert.Equal(TimeSpan.FromSeconds(6),Dispatcher.Backoff(0,1.2));Assert.Equal(TimeSpan.FromHours(1),Dispatcher.Backoff(20,1.2));}
    [Fact]public async Task AuthenticatedHeartbeatIsPersistedWithoutExposingToken(){var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");try{var q=new OutboundQueue(p);var handler=new Handler(r=>{Assert.Equal(HttpMethod.Head,r.Method);Assert.Equal("Bearer",r.Headers.Authorization?.Scheme);Assert.Equal("secret-token",r.Headers.Authorization?.Parameter);Assert.True(r.Headers.Contains("X-Jellyfin-Server-Version"));return new(HttpStatusCode.NoContent);});var d=new Dispatcher(new HttpClient(handler),q,()=>(new Uri("http://127.0.0.1:1/"),"secret-token"));await d.ProbeAsync("10.11.0","0.1.0.2");var status=await q.StatusAsync();Assert.NotNull(status.LastProbeAt);Assert.Null(status.LastProbeErrorCode);var stored=await File.ReadAllTextAsync(p);Assert.DoesNotContain("secret-token",stored);}finally{File.Delete(p);}}
    [Fact]public void ManualCaptureAcceptsJellyfinManualPlayedReasons(){Assert.True(WatchWeaverHostedService.IsManualPlayedChange("TogglePlayed",true));Assert.True(WatchWeaverHostedService.IsManualPlayedChange("UpdateUserData",true));Assert.False(WatchWeaverHostedService.IsManualPlayedChange("UpdateUserRating",true));Assert.False(WatchWeaverHostedService.IsManualPlayedChange("TogglePlayed",false));}
    [Fact]public async Task ReconciliationPersistsEvidenceAndNeverInventsOldWatches(){var p=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");try{var now=DateTimeOffset.Parse("2026-09-05T12:00:00Z");var state=new ReconciliationState(p);Assert.True(await state.ObserveAsync("u","i",1,now.AddMinutes(-5),now,TimeSpan.FromHours(24)));Assert.False(await state.ObserveAsync("u","i",1,now.AddMinutes(-5),now,TimeSpan.FromHours(24)));var restarted=new ReconciliationState(p);await restarted.LoadAsync();Assert.False(await restarted.ObserveAsync("u","i",1,now.AddMinutes(-5),now,TimeSpan.FromHours(24)));Assert.False(await restarted.ObserveAsync("u","old",4,now.AddDays(-30),now,TimeSpan.FromHours(24)));Assert.True(await restarted.ObserveAsync("u","i",2,now.AddMinutes(-1),now,TimeSpan.FromHours(24)));}finally{File.Delete(p);}}
    private sealed class Handler(Func<HttpRequestMessage,HttpResponseMessage> f):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken c)=>Task.FromResult(f(r));}
}
